<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE officeDesk [
    <!ELEMENT officeDesk (item*)>
    <!ELEMENT item (color, weight, dimensions, purchaseDate, condition)>
    <!ATTLIST item
        type CDATA #REQUIRED
        brand CDATA #REQUIRED
        model CDATA #REQUIRED
        price CDATA #REQUIRED>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT weight (#PCDATA)>
    <!ELEMENT dimensions (#PCDATA)>
    <!ELEMENT purchaseDate (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>
<officeDesk>
    <item type="Laptop" brand="Dell" model="XPS 13" price="1000">
        <color>Silver</color>
        <weight>1.2 kg</weight>
        <dimensions>302mm x 199mm x 15mm</dimensions>
        <purchaseDate>2022-01-15</purchaseDate>
        <condition>New</condition>
    </item>
    <item type="Monitor" brand="Samsung" model="Odyssey G7" price="700">
        <color>Black</color>
        <weight>7.2 kg</weight>
        <dimensions>614mm x 306mm x 576mm</dimensions>
        <purchaseDate>2021-12-01</purchaseDate>
        <condition>New</condition>
    </item>
    <item type="Keyboard" brand="Logitech" model="MX Keys" price="100">
        <color>Black</color>
        <weight>0.81 kg</weight>
        <dimensions>430mm x 131mm x 21mm</dimensions>
        <purchaseDate>2020-11-20</purchaseDate>
        <condition>Used</condition>
    </item>
    <item type="Mouse" brand="Logitech" model="MX Master 3" price="100">
        <color>Black</color>
        <weight>0.14 kg</weight>
        <dimensions>125mm x 84mm x 51mm</dimensions>
        <purchaseDate>2019-08-25</purchaseDate>
        <condition>Used</condition>
    </item>
    <item type="Notebook" brand="Moleskine" model="Classic" price="20">
        <color>Black</color>
        <weight>0.25 kg</weight>
        <dimensions>210mm x 130mm x 15mm</dimensions>
        <purchaseDate>2023-04-10</purchaseDate>
        <condition>New</condition>
    </item>
</officeDesk>
